# Generated by Django 5.2.5 on 2025-08-16 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='oficina.oficina'),
        ),
    ]
